"""Add ExportFile entity, Add Task discriminator

Revision ID: 0e57d03bc767
Revises: 2cd829f0a3fe
Create Date: 2025-10-31 15:57:24.168712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e57d03bc767"
down_revision: Union[str, None] = "2cd829f0a3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the task_type ENUM type first
    task_type_enum = sa.Enum("object_search", "photometric_data", name="task_type")
    task_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "ac_export_file",
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "export_option",
            sa.Enum("single_file", "by_sources", "raw_data", name="export_option"),
            nullable=False,
        ),
        sa.Column("task_set_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "ac_plugin", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column("ac_task", sa.Column("task_type", task_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ac_task", "task_type")
    op.alter_column(
        "ac_plugin", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_table("ac_export_file")

    sa.Enum(name="task_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
