"""tasks table

Revision ID: 13331b4ec65f
Revises: 320b802e2dd5
Create Date: 2025-07-29 18:26:01.020811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13331b4ec65f"
down_revision: Union[str, None] = "320b802e2dd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ac_task",
        sa.Column(
            "status",
            sa.Enum("in_progress", "completed", "failed", name="taskstatus"),
            nullable=False,
        ),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "ac_photometric_data", "ac_task", ["task_id"], ["id"])
    op.create_foreign_key(
        None, "ac_stellar_object_identifier", "ac_task", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ac_stellar_object_identifier", type_="foreignkey")
    op.drop_constraint(None, "ac_photometric_data", type_="foreignkey")
    op.drop_table("ac_task")
    # ### end Alembic commands ###
