"""tasks polymorphism

Revision ID: 1b67ca29f0c4
Revises: 13331b4ec65f
Create Date: 2025-07-29 21:48:34.211782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b67ca29f0c4"
down_revision: Union[str, None] = "13331b4ec65f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ac_task_result",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["ac_task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("ac_photometric_data_task_id_fkey"),
        "ac_photometric_data",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "ac_photometric_data", "ac_task_result", ["id"], ["id"])
    op.drop_column("ac_photometric_data", "task_id")
    op.drop_constraint(
        op.f("ac_stellar_object_identifier_task_id_fkey"),
        "ac_stellar_object_identifier",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "ac_stellar_object_identifier", "ac_task_result", ["id"], ["id"]
    )
    op.drop_column("ac_stellar_object_identifier", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_stellar_object_identifier",
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "ac_stellar_object_identifier", type_="foreignkey")
    op.create_foreign_key(
        op.f("ac_stellar_object_identifier_task_id_fkey"),
        "ac_stellar_object_identifier",
        "ac_task",
        ["task_id"],
        ["id"],
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "ac_photometric_data", type_="foreignkey")
    op.create_foreign_key(
        op.f("ac_photometric_data_task_id_fkey"),
        "ac_photometric_data",
        "ac_task",
        ["task_id"],
        ["id"],
    )
    op.drop_table("ac_task_result")
    # ### end Alembic commands ###
