"""add plugin id column

Revision ID: 20b74b65090f
Revises: 80b7e16d0ace
Create Date: 2025-07-30 12:49:40.729856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20b74b65090f"
down_revision: Union[str, None] = "80b7e16d0ace"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_photometric_data", sa.Column("plugin_id", sa.Uuid(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ac_photometric_data", "plugin_id")
    # ### end Alembic commands ###
