"""add url and description to catalog model

Revision ID: 2cd829f0a3fe
Revises: e478fa8d63f3
Create Date: 2025-09-22 14:49:54.853007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cd829f0a3fe"
down_revision: Union[str, None] = "e478fa8d63f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ac_plugin", sa.Column("catalog_url", sa.String(), nullable=False))
    op.add_column("ac_plugin", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ac_plugin", "description")
    op.drop_column("ac_plugin", "catalog_url")
    # ### end Alembic commands ###
