"""database tables for tasks

Revision ID: 320b802e2dd5
Revises: a1b6e3b23b06
Create Date: 2025-07-25 23:31:53.442034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "320b802e2dd5"
down_revision: Union[str, None] = "a1b6e3b23b06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ac_photometric_data",
        sa.Column("julian_date", sa.Double(), nullable=False),
        sa.Column("magnitude", sa.Double(), nullable=False),
        sa.Column("magnitude_err", sa.Double(), nullable=False),
        sa.Column("b_magnitude", sa.Double(), nullable=True),
        sa.Column("b_magnitude_err", sa.Double(), nullable=True),
        sa.Column("v_magnitude", sa.Double(), nullable=True),
        sa.Column("v_magnitude_err", sa.Double(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ac_stellar_object_identifier",
        sa.Column(
            "identifier", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ac_stellar_object_identifier")
    op.drop_table("ac_photometric_data")
    # ### end Alembic commands ###
