"""add task relationships

Revision ID: 5157397eb9a4
Revises: aad13fc3f8d7
Create Date: 2025-08-27 11:21:20.173500

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5157397eb9a4"
down_revision: Union[str, None] = "aad13fc3f8d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "ac_photometric_data", "ac_task", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "ac_stellar_object_identifier",
        "ac_task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ac_stellar_object_identifier", type_="foreignkey")
    op.drop_constraint(None, "ac_photometric_data", type_="foreignkey")
    # ### end Alembic commands ###
