"""rename photometric data columns

Revision ID: 84c7c6251709
Revises: 20b74b65090f
Create Date: 2025-07-30 13:32:07.623790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84c7c6251709"
down_revision: Union[str, None] = "20b74b65090f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_photometric_data", sa.Column("magnitude_error", sa.Double(), nullable=False)
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column("b_magnitude_error", sa.Double(), nullable=True),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column("v_magnitude_error", sa.Double(), nullable=True),
    )
    op.drop_column("ac_photometric_data", "b_magnitude_err")
    op.drop_column("ac_photometric_data", "magnitude_err")
    op.drop_column("ac_photometric_data", "v_magnitude_err")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "v_magnitude_err",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "magnitude_err",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "b_magnitude_err",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("ac_photometric_data", "v_magnitude_error")
    op.drop_column("ac_photometric_data", "b_magnitude_error")
    op.drop_column("ac_photometric_data", "magnitude_error")
    # ### end Alembic commands ###
