"""add object identification flag

Revision ID: 92c060fc23cf
Revises: 5157397eb9a4
Create Date: 2025-09-08 17:27:54.574652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92c060fc23cf"
down_revision: Union[str, None] = "5157397eb9a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_plugin",
        sa.Column("directly_identifies_objects", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ac_plugin", "directly_identifies_objects")
    # ### end Alembic commands ###
