"""add light filter column

Revision ID: aad13fc3f8d7
Revises: 84c7c6251709
Create Date: 2025-07-30 20:48:40.567489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aad13fc3f8d7"
down_revision: Union[str, None] = "84c7c6251709"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_photometric_data", sa.Column("light_filter", sa.String(), nullable=True)
    )
    op.drop_column("ac_photometric_data", "b_magnitude_error")
    op.drop_column("ac_photometric_data", "b_magnitude")
    op.drop_column("ac_photometric_data", "v_magnitude_error")
    op.drop_column("ac_photometric_data", "v_magnitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "v_magnitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "v_magnitude_error",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "b_magnitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ac_photometric_data",
        sa.Column(
            "b_magnitude_error",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("ac_photometric_data", "light_filter")
    # ### end Alembic commands ###
