"""joined tasks

Revision ID: b1109fb03411
Revises: 1b67ca29f0c4
Create Date: 2025-07-30 10:44:21.807483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1109fb03411"
down_revision: Union[str, None] = "1b67ca29f0c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ac_task", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ac_task",
        sa.Column(
            "status",
            postgresql.ENUM("in_progress", "completed", "failed", name="taskstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
