name: Code Quality
on:
  push:
    paths:
      - ac-backend/**

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff linting
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./ac-backend/src"

  mypy:
    needs: ruff
    runs-on: ubuntu-latest
    name: Mypy type check
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "ac-backend/pyproject.toml"
    - name: Install the project
      run: uv sync --locked --all-extras --dev
      working-directory: ac-backend
    - name: Run mypy
      run: uv run mypy src --strict
      working-directory: ac-backend
